1. Variables and basic arithmetic

In [1]:
systolic = 148
diastolic = 92
pulse_pressure = systolic - diastolic

print(pulse_pressure)

56

2. More calculations: average BP

In [2]:
readings = [142, 136, 150]

mean_sbp = sum(readings) / len(readings)
print(round(mean_sbp, 1))

142.7

3. Comparisons return True or False

In [3]:
sbp = 145

print(sbp >= 140)
print(sbp < 120)
print(sbp == 145)

True
False
True

4. if / else: Choose one path

In [4]:
sbp = 145

if sbp >= 140:
    print("Review elevated reading")
else:
    print("Below example threshold")

Review elevated reading

5. if / elif / else: Multiple branches

In [5]:
sbp = 128

if sbp < 120:
    label = "Below 120"
elif sbp < 140:
    label = "120 to 139"
else:
    label = "140 or higher"

print(label)

120 to 139

6. Combining conditions with and / or

In [6]:
sbp = 146
dbp = 86

if sbp >= 140 or dbp >= 90:
    print("Flag for review")

if sbp >= 140 and dbp >= 90:
    print("Both meet thresholds")

Flag for review

7. for loops: One action, many values

In [7]:
sbp_readings = [118, 135, 149]

for sbp in sbp_readings:
    print("Systolic:", sbp)

Systolic: 118
Systolic: 135
Systolic: 149

8. for + if: Count flagged readings

In [8]:
sbp_readings = [118, 135, 149, 155]
flagged = 0

for sbp in sbp_readings:
    if sbp >= 140:
        flagged += 1

print("Flagged:", flagged)

Flagged: 2

9. Loop over medication records

In [9]:
medications = [
    "lisinopril",
    "metoprolol",
    "atorvastatin"
]

for medication in medications:
    print("Medication:", medication)

Medication: lisinopril
Medication: metoprolol
Medication: atorvastatin

10. while loops: Repeat until a condition changes

In [10]:
count = 1

while count <= 3:
    print("Check", count)
    count += 1

Check 1
Check 2
Check 3

11. while loop: Stop when the goal is met

In [11]:
readings = [151, 146, 138, 132]
i = 0

while i < len(readings) and readings[i] >= 140:
    print("Review:", readings[i])
    i += 1

print("Stopped at index:", i)

Review: 151
Review: 146
Stopped at index: 2

In [13]:
from pathlib import Path

print("Current directory:", Path.cwd())

root = Path("/workspaces/hi5304-notebooks")

for name in ["patients.csv", "medications.csv", "BP_readings.csv"]:
    matches = list(root.rglob(name))
    print(f"\n{name}:")
    if matches:
        for path in matches[:10]:
            print(" ", path)
    else:
        print("  Not found")

Current directory: /workspaces/hi5304-notebooks/learning/hi5312

patients.csv:
  /workspaces/hi5304-notebooks/learning/patients.csv
  /workspaces/hi5304-notebooks/data/patients.csv
  /workspaces/hi5304-notebooks/data/chronic/patients.csv
  /workspaces/hi5304-notebooks/data/oncology/patients.csv
  /workspaces/hi5304-notebooks/data/mimic-iv-demo/hosp/patients.csv

medications.csv:
  /workspaces/hi5304-notebooks/data/medications.csv
  /workspaces/hi5304-notebooks/data/chronic/medications.csv

BP_readings.csv:
  Not found

12. Load our course CSV datasets

In [14]:
from pathlib import Path
import pandas as pd
import numpy as np

# Course data directory
data_dir = Path("/workspaces/hi5304-notebooks/data")

# Load existing datasets
patients = pd.read_csv(data_dir / "patients.csv")
medications = pd.read_csv(data_dir / "medications.csv")

# Display actual columns
print("Patients columns:", patients.columns.tolist())
print("Medications columns:", medications.columns.tolist())

# Create synthetic BP readings for teaching
rng = np.random.default_rng(42)

# Use patient IDs from the existing patient dataset
patient_ids = patients["patient_id"].dropna().unique()

BP_readings = pd.DataFrame({
    "patient_id": rng.choice(patient_ids, size=100, replace=True),
    "systolic": rng.integers(105, 175, size=100),
    "diastolic": rng.integers(60, 105, size=100)
})

print("\nDatasets loaded successfully!")
print("Patients:", patients.shape)
print("Medications:", medications.shape)
print("BP readings:", BP_readings.shape)

display(BP_readings.head())

Patients columns: ['patient_id', 'first_name', 'last_name', 'date_of_birth', 'sex', 'race', 'ethnicity', 'zip_code']
Medications columns: ['med_id', 'patient_id', 'medication_name', 'dose', 'frequency', 'start_date', 'indication']

Datasets loaded successfully!
Patients: (5, 8)
Medications: (5, 7)
BP readings: (100, 3)

   patient_id  systolic  diastolic
0        1001       163         76
1        1004       118        100
2        1004       161         82
3        1003       105         91
4        1003       160         80

In [15]:
BP_readings.to_csv(
    data_dir / "BP_readings.csv",
    index=False
)

print("Saved:", data_dir / "BP_readings.csv")

Saved: /workspaces/hi5304-notebooks/data/BP_readings.csv

In [16]:
print("Patients:", len(patients))
print("Medications:", len(medications))
print("BP readings:", len(BP_readings))

print("\nMissing values:")
print(BP_readings.isna().sum())

print("\nBP summary:")
display(BP_readings[["systolic", "diastolic"]].describe())

print("\nUnique patients with BP readings:")
print(BP_readings["patient_id"].nunique())

Patients: 5
Medications: 5
BP readings: 100

Missing values:
patient_id    0
systolic      0
diastolic     0
dtype: int64

BP summary:

         systolic   diastolic
count  100.000000  100.000000
mean   138.880000   81.090000
std     19.354367   12.119018
min    105.000000   60.000000
25%    124.000000   71.750000
50%    139.000000   81.000000
75%    154.250000   91.000000
max    174.000000  104.000000

Unique patients with BP readings:
5

13. Inspect before calculating

In [17]:
print(patients.shape)
print(medications.columns.tolist())
print(BP_readings.head())

print(BP_readings.isna().sum())

(5, 8)
['med_id', 'patient_id', 'medication_name', 'dose', 'frequency', 'start_date', 'indication']
   patient_id  systolic  diastolic
0        1001       163         76
1        1004       118        100
2        1004       161         82
3        1003       105         91
4        1003       160         80
patient_id    0
systolic      0
diastolic     0
dtype: int64

14. Calculations with pandas

In [18]:
BP_readings["pulse_pressure"] = (
    BP_readings["systolic"]
    - BP_readings["diastolic"]
)

print(BP_readings["pulse_pressure"].mean())

57.79

15. Conditional columns with pandas

In [19]:
BP_readings["review_flag"] = (
    BP_readings["systolic"] >= 140
)

print(BP_readings["review_flag"].value_counts())

review_flag
False    51
True     49
Name: count, dtype: int64

16. Summarize by patient

In [20]:
summary = (BP_readings
    .groupby("patient_id")
    .agg(mean_sbp=("systolic", "mean"),
         n_readings=("systolic", "count"))
    .reset_index()
)

print(summary.head())

   patient_id    mean_sbp  n_readings
0        1001  142.388889          18
1        1002  136.266667          15
2        1003  131.227273          22
3        1004  138.769231          26
4        1005  146.631579          19

17. Join patients to BP summaries

In [21]:
patient_summary = patients.merge(
    summary,
    on="patient_id",
    how="left",
    validate="one_to_one"
)

print(patient_summary.head())

   patient_id first_name last_name date_of_birth sex      race     ethnicity  \
0        1001       John       Doe     4/12/1968   M     White  Non-Hispanic
1        1002      Maria     Lopez     9/30/1975   F  Hispanic      Hispanic
2        1003      James     Smith     1/18/1982   M     Black  Non-Hispanic
3        1004      Linda      Chen      6/5/1990   F     Asian  Non-Hispanic
4        1005     Robert   Johnson    11/22/1959   M     White  Non-Hispanic

   zip_code    mean_sbp  n_readings
0     75201  142.388889          18
1     75204  136.266667          15
2     75080  131.227273          22
3     75024  138.769231          26
4     75230  146.631579          19

A. Write an if/else rule for a systolic reading of 132.

In [22]:
systolic_bp = 132

if systolic_bp >= 130:
    print("Systolic BP is 130 or higher")
else:
    print("Systolic BP is below 130")

Systolic BP is 130 or higher

B. Use a for loop to count values ≥ 140 in [125, 142, 138, 151].

In [23]:
bp_readings = [125, 142, 138, 151]
count = 0

for bp in bp_readings:
    if bp >= 140:
        count += 1

print("Readings >= 140:", count)

Readings >= 140: 2

C. Use a while loop to print the numbers 1 through 5.

In [24]:
number = 1

while number <= 5:
    print(number)
    number += 1

1
2
3
4
5

D. Calculate the average of [130, 135, 145].

In [ ]:
bp_readings = [130, 135, 145]

total = sum(bp_readings)
count = len(bp_readings)
average = total / count

print(f"Average systolic BP: {average:.1f} mmHg")

Average systolic BP: 140.5 mmHg